[package]
name = "luce_textmate"
source = "src"

[dependencies]
luce_regex = "../luce-regex"

[exports]
tm_json = "luce_textmate.json"
tm_grammar = "luce_textmate.grammar"
tm_tokenizer = "luce_textmate.tokenizer"
